### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by mjhart** [MattBlack85/aldebaran#1]
I would like to use this API in a web app I am working on. However, the API does not enable CORS, preventing browsers from making direct requests to the API.

**Comment by MattBlack85** [comment]
hey @mjhart which domain exactly? adding cors shouldn't be a big deal anyway I do not plan to use a *

**Comment by mjhart** [comment]
I don't have a domain yet. Curious why you don't want to use * ?

**Comment by MattBlack85** [comment]
@mjhart  allowing fetching data from web apps without cors could lead to abuses, knowing which domains are requesting data will make easier to throttle per domain
